### ISSUE TITLE
Making a branch (hack.af/draw-dino)

### ISSUE THREAD

**Issue by exu3** [hackclub/draw-dino#17]
On hack.af/draw-dino, users are instructed to create a branch, but users who are not yet a part of the `hackclub` org seem not to have the permissions to make a branch.

**Comment by eilla1** [comment]
Is there a way to update the permissions so that anyone can make a branch, or would hack.af/draw-dino instructions have to be changed?

**Comment by exu3** [comment]
This doesn't seem to be an issue because people can join the `hackclub` org before submitting their dino.
