### ISSUE TITLE
Slack app called "make-dino" instead of "draw-dino"

### ISSUE THREAD

**Issue by zachlatta** [hackclub/draw-dino#25]
Right now, across the branding for this project we use "draw-dino" as the word for the project. Ex. hack.af/draw-dino, repo name, etc.

When you try to sign in with Slack, the Slack app's name is `make-dino`. I propose we change it to `draw-dino` so it's consistent.

<img width="1552" alt="Screen Shot 2022-03-17 at 12 14 52 PM" src="https://user-images.githubusercontent.com/992248/158845019-b553c3f7-b5d7-44ee-a5dc-04ece6e5fba6.png">

**Comment by JosiasAurel** [comment]
The slack app has been renamed to `draw-dino`
