### ISSUE TITLE
Link to GitHub repo prominently from website

### ISSUE THREAD

**Issue by zachlatta** [hackclub/draw-dino#26]
In the spirit of making Hack Club feel "editable", what if the homepage of https://hack.af/draw-dino had a link to this GitHub repo, so people can see the code for the site and make PRs themselves?

**Comment by geeky-sambhav** [comment]
I would like to contribute to this

**Comment by grymmy** [comment]
Resolved - The page has a "copy this" link as seen here (I didn't do it - just observing it's been done).
<img width="699" alt="Screenshot 2024-04-02 at 5 03 18 PM" src="https://github.com/hackclub/draw-dino/assets/43505167/394793ea-1d06-4af7-9f77-d29e6274dd68">
