### ISSUE TITLE
Small "how to star" GIF

### ISSUE THREAD

**Issue by zachlatta** [hackclub/draw-dino#27]
On this step of the flow, the GIF showing you how to star the hackclub/dinosaurs repo is super tiny. It'd be great if it took up all the available space on the left side of the screen.

<img width="1552" alt="Screen Shot 2022-03-17 at 12 17 54 PM" src="https://user-images.githubusercontent.com/992248/158845522-00bac5a3-0f90-4f40-848a-e5377706ce5f.png">

**Comment by jessicard** [comment]
Oooh yeah. As a note, it looks like the [gif itself](https://draw-dino.hackclub.com/steps/star.gif) is tiny, so just increasing the size will make it low quality. Probably need to re-record it higher res, and make the recording short, so it's not too big of a file.

**Comment by exu3** [comment]
`https://cloud-kd8jtl2el-hack-club-bot.vercel.app/0star-it.gif` is a slightly larger one.

<img src="https://cloud-kd8jtl2el-hack-club-bot.vercel.app/0star-it.gif">
